-- ==============================================================================
-- SIGAP — Vistas analíticas: OBSOLETAS
-- Universidad CESMAG
-- ==============================================================================
--
-- Estas 4 vistas se crearon para alimentar Power BI por DirectQuery. Al
-- retirarse Power BI y construirse la analítica nativa (React + Recharts
-- sobre /api/analitica), dejaron de tener consumidor.
--
-- La auditoría del 19/09/2026 sobre la base de producción encontró además
-- que estaban defectuosas:
--
--   v_analitica_seguimiento_cortes
--       Devolvía 0 filas siempre: hace INNER JOIN contra actividad_semana,
--       que está vacía (0 registros).
--
--   v_analitica_cumplimiento_docente
--       ejecucion_total y porcentaje_avance_calculado daban 0 para todos los
--       docentes, por la misma razón. Además arrastraba un join cartesiano
--       contra actividad_semana + resultados que habría duplicado las horas
--       en el momento en que esa tabla se poblara, y usaba
--       COALESCE(tc.horas_contrato, 40), que distorsiona a los docentes de
--       medio tiempo y hora cátedra.
--
--   v_analitica_kpis_programa
--       Clasificaba los estados buscando 'aceptada', 'en revision' y
--       'rechazada'. Los valores reales son 'Aceptado', 'Pendiente',
--       'Aprobada' y 'Devuelta', de modo que los docentes en 'Aceptado'
--       (el estado más frecuente) no entraban en ninguna categoría.
--       Pese al nombre, tampoco agrupaba por programa: no proyectaba
--       id_programa en ninguna parte.
--
--   v_analitica_distribucion_funciones
--       Sin id_programa, por lo que no se podía filtrar por programa, y
--       sumaba las horas de las funciones del catálogo maestro (plantillas
--       sin docente asignado), inflando los totales.
--
-- La analítica vigente vive en:
--   backend/controllers/analiticaController.js  (consultas parametrizadas)
--   backend/config/catalogoAnalitica.js         (metadatos de indicadores)
--
-- Allí las consultas aceptan id_periodo e id_programa como parámetros,
-- excluyen el catálogo maestro uniendo contra usuario_asignacion y protegen
-- las divisiones con NULLIF.
--
-- ------------------------------------------------------------------------------
-- Para eliminar las vistas de la base de datos (opcional; mientras existan
-- no hacen daño, simplemente nadie las consulta):
-- ------------------------------------------------------------------------------

-- DROP VIEW IF EXISTS v_analitica_cumplimiento_docente;
-- DROP VIEW IF EXISTS v_analitica_distribucion_funciones;
-- DROP VIEW IF EXISTS v_analitica_seguimiento_cortes;
-- DROP VIEW IF EXISTS v_analitica_kpis_programa;
